datadir: datasets/lichess_300_1200_0924/split_30_11_900208/elos/2200
elo_edges: [1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600]
model_args:
  dim: 2048 
  n_layers: 16 
  n_classifier_layers: 15
  n_heads: 32
  n_kv_heads: 8 
  vocab_size: 2048
  multiple_of: 256
  ffn_dim_multiplier: 1.5 
  norm_eps: 1.e-5
  rope_theta: 10000
  max_seq_len: 128
lr_scheduler_params:
  lr: 3.e-4
  name: "WarmUpCosine"
  min_lr: 3.e-6
  warmup_steps: 5000 
batch_size: 64 
max_steps: 2.e+5 
val_check_steps: 50000
strategy: fsdp 
random_seed: 0
