datadir: datasets/lichess_300_1200_0924/split_30_11_900208
model_args:
  dim: 2048 
  n_layers: 16 
  n_heads: 32
  n_kv_heads: 8 
  vocab_size: 2048
  multiple_of: 256
  ffn_dim_multiplier: 1.5 
  norm_eps: 1.e-5
  rope_theta: 10000
  max_batch_size: 512 
  max_seq_len: 128
lr_scheduler_params:
  lr: 3.e-4
  name: "WarmUpCosine"
  min_lr: 3.e-6
  warmup_steps: 8000
batch_size: 32 
max_steps: 1.e+6 
val_check_steps: 50000
strategy: fsdp 
random_seed: 0
