#datadir: pgn/test_npy
datadir: datasets/lichess_300_1200_0924/split_30_11_900505
dataset_p: 0.1
elo_edges: [1200,1400,1600,1800,2000,2200,2400,2600]
model_args:
  dim: 512 
  n_layers: 16 
  n_heads: 32
  n_kv_heads: 8 
  vocab_size: 2048
  multiple_of: 256
  ffn_dim_multiplier: 1.5 
  norm_eps: 1.e-5
  rope_theta: 10000
  max_batch_size: 256 
  max_seq_len: 128
lr_scheduler_params:
  lr: 3.e-4
  name: "WarmUpCosine"
  min_lr: 3.e-6
  warmup_steps: 8000
batch_size: 256
max_steps: 1.e+6 
val_check_steps: 50000
strategy: ddp
random_seed: 0
