datadir: datasets/lichess_180_10800_60_122024_v2/split_11_10_10m_tc600
elo_params:
  predict: True
  loss: gaussian_nll 
  initial_var: 1
  warmup_elo_steps: 0
  warmup_var_steps: 0
  weight: 1
  edges: [4000]
tc_groups: 
  10800: [1000]
model_args:
  predict_move: True
  dim: 2048 
  n_layers: 16
  n_heads: 32
  n_kv_heads:  
  vocab_size: 2048
  multiple_of: 256
  ffn_dim_multiplier: 1.5 
  norm_eps: 1.e-5
  rope_theta: 10000
  max_seq_len: 150
lr_scheduler_params:
  lr: 3.e-4
  name: "WarmUpCosine"
  min_lr: 3.e-6
  warmup_steps: 25000
accumulate_grad_batches: 1
opening_moves: 0
batch_size: 4 
max_steps: 1.e+6 
val_check_steps: 25000
strategy: ddp
random_seed: 0
