datadir: datasets/lichess_180_10800_60_122024/split_21_30_100k_900208
elo_edges: [1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600]
model_args:
  dim: 1024 
  n_layers: 16 
  n_heads: 32
  n_kv_heads: 8 
  vocab_size: 2048
  multiple_of: 256
  ffn_dim_multiplier: 1.5 
  norm_eps: 1.e-5
  rope_theta: 10000
  max_seq_len: 128
lr_scheduler_params:
  lr: 5.e-5
  name: "WarmUpCosine"
  min_lr: 1.e-7
  warmup_steps: 25000 
batch_size: 256 
max_steps: 4.e+5 
val_check_steps: 25000
strategy: ddp 
random_seed: 0
