model_args:
  dim: 1024
  n_layers: 16
  n_heads: 32
  n_kv_heads: 8
  multiple_of: 256
  ffn_dim_multiplier: 1.5 
  norm_eps: 1.e-5
  rope_theta: 10000
  max_seq_len: 768 
lr_scheduler_params:
  lr: 3.e-4
  name: "WarmUpCosine"
  min_lr: 3.e-6
  warmup_steps: 25000
max_elo_group: 2600
min_timectl: 300
max_repeats: 10
accumulate_grad_batches: 16
batch_size: 4 
max_steps: 8.e+6
val_check_steps: 50000 
strategy: auto 
random_seed: 0
