datadir: datasets/lichess_300_1200_0924/split_30_11_900208/elos
model_args:
  dim: 512 
  n_layers: 16 
  n_heads: 32
  n_kv_heads: 8 
  vocab_size: 2048
  multiple_of: 256
  ffn_dim_multiplier: 1.5 
  norm_eps: 1.e-5
  rope_theta: 10000
  max_batch_size: 256 
  max_seq_len: 128
lr_scheduler_params:
  lr: 3.e-4
  name: "Cosine"
  min_lr: 3.e-6
batch_size: 256
max_steps: 5.e+4 
val_check_steps: 25000
strategy: ddp
random_seed: 0
