datadir: datasets/debug/filtered
elo_params:
  predict: True
  loss: gaussian_nll
  initial_var: 1.e-1
  warmup_var_steps: 0 
  warmup_elo_steps: 0   
  weight: 1
  edges: [4000]
tc_groups: 
 10800: [1000]
model_args:
  predict_move: True
  dim: 64 
  n_layers: 16 
  n_heads: 32
  n_kv_heads: 8 
  vocab_size: 2048
  multiple_of: 256
  ffn_dim_multiplier: 1.5 
  norm_eps: 1.e-5
  rope_theta: 10000
  max_seq_len: 128
lr_scheduler_params:
  lr: 3.e-4
  name: "WarmUpCosine"
  min_lr: 3.e-6
  warmup_steps: 8000
opening_moves: 0
batch_size: 32 
max_steps: 10 
val_check_steps: 10 
strategy: auto 
random_seed: 0
