name: base 
channels:
  - pytorch
  - nvidia
dependencies:
  - anaconda::python=3.10
  - anaconda::numpy=1.26
  - conda-forge::matplotlib
  - anaconda::pyyaml
  - conda-forge::chess
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - conda-forge::lightning
  - conda-forge::tensorboard
  - conda-forge::chess
  - conda-forge::python-wget
  - anaconda::pip
  - pip:
      - fairscale

