name: mimicChess
dependencies:
  - python=3.10
  - "numpy<2.0"
  - matplotlib
  - pyyaml
  - conda-forge::chess
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  - conda-forge::lightning
  - conda-forge::tensorboard
  - pip
  - pip:
      - fairscale

