name: base 
  - pytorch
dependencies:
  - anaconda::python=3.10
  - anaconda::numpy=1.26
  - conda-forge::matplotlib
  - anaconda::pyyaml
  - conda-forge::chess
  - pytorch
  - torchvision
  - torchaudio
  - conda-forge::lightning
  - conda-forge::tensorboard
  - conda-forge::chess
  - anaconda::pip
  - pip:
      - fairscale

