name: base 
channels:
  - pytorch
  - nvidia
dependencies:
  - anaconda::python=3.10
  - anaconda::"numpy<2.0"
  - anacond::matplotlib
  - anaconda::pyyaml
  - conda-forge::chess
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - conda-forge::lightning
  - conda-forge::tensorboard
  - anaconda::pip
  - pip:
      - fairscale

