name: base
dependencies:
  - anaconda::python=3.11
  - anaconda::pip
  - conda-forge::tensorboard
  - conda-forge::matplotlib
  - pip:
      - autopep8
      - numpy
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch
      - torchvision
      - torchaudio
      - torchdata
      - lightning
      - python-chess
      - tokenizers
      - pyarrow
      - tiktoken