name: base
dependencies:
  - anaconda::python=3.10
  - anaconda::pip
  - pip:
      - autopep8
      - numpy==1.26
      - matplotlib
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch
      - torchvision
      - torchaudio
      - lightning
      - fairscale
      - tensorboard
      - python-chess
